import{a as w,i,S}from"./assets/vendor-b42c18af.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function n(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();async function x(){const t=$.value.trim().split(",").join("+"),r=new URLSearchParams({key:"42633759-4a44573e34755b4488adb4c1b",q:[t],image_type:"photo",orientation:"horizontal",safesearch:!0,page:[l],per_page:[f]}),s=await w.get(`https://pixabay.com/api/?${r}`);return F(d),s.data}function E(t){if(t.length==0)i.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});else{const r=t.map(({largeImageURL:s,webformatURL:n,tags:e,likes:o,views:a,comments:L,downloads:P})=>`<li class="photos-list-item">
            <a class="photos-list-link" href="${s}">
            <img class="photo" src="${n}" alt="${e}"/>
            </a>
            <ul class="photo-information-container">
            <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${o}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${a}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${L}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${P}</p></li>
            </ul>
            </li>`).join("");h.insertAdjacentHTML("beforeend",r),q.refresh()}}const c=document.querySelector(".search-form"),$=c.elements.search,p=document.querySelector(".next-page-btn");m(p);const h=document.querySelector(".gallery"),q=new S(".gallery a",{captionsData:"alt",captionDelay:250}),d=document.querySelector(".loader");m(d);let l=1,f=15,g=Number,u="";c.addEventListener("submit",y);p.addEventListener("click",v);async function y(t){t.preventDefault(),h.innerHTML="";const r=t.target.elements.search.value.trim();if(r==="")return i.show({message:"Please complete the field!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});r!==u?(l=1,u=r):l+=1;try{const s=await x();E(s.hits),g=Math.ceil(s.totalHits/f),F(p)}catch(s){console.log(s),i.error({message:"Sorry, an error occurred while loading. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}finally{m(d),b(),c.reset()}}window.onload=b;async function v(){if(l>g)return i.error({theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight",message:"We're sorry, there are no more posts to load"});await y()}function F(t){t.classList.toggle("hidden"),t.style.display="flex"}function m(t){t.classList.toggle("hidden"),t.style.display="none"}function b(){document.body.classList.add("loaded"),document.body.classList.remove("loaded_hiding")}
//# sourceMappingURL=commonHelpers.js.map
