import{a as P,i as p,S}from"./assets/vendor-b42c18af.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&c(n)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function c(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();async function x(){let e;i===1?e=O.value.trim().split(" ").join("+"):e=m.trim().split(" ").join("+");const r=new URLSearchParams({key:"42633759-4a44573e34755b4488adb4c1b",q:[e],image_type:"photo",orientation:"horizontal",safesearch:!0,page:[i],per_page:[g]});return(await P.get(`https://pixabay.com/api/?${r}`)).data}function E(e){if(e.length==0)p.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});else{const r=e.map(({largeImageURL:s,webformatURL:c,tags:t,likes:o,views:n,comments:L,downloads:w})=>`<li class="photos-list-item">
            <a class="photos-list-link" href="${s}">
            <img class="photo" src="${c}" alt="${t}"/>
            </a>
            <ul class="photo-information-container">
            <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${o}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${n}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${L}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${w}</p></li>
            </ul>
            </li>`).join("");h.insertAdjacentHTML("beforeend",r),q.refresh()}}const u=document.querySelector(".search-form"),O=u.elements.search,a=document.querySelector(".next-page-btn");l(a);const h=document.querySelector(".gallery"),q=new S(".gallery a",{captionsData:"alt",captionDelay:250}),d=document.querySelector(".loader");l(d);let i=1,g=15,y=Number,m="";window.onload=b;u.addEventListener("submit",v);a.addEventListener("click",$);async function v(e){e.preventDefault(),h.innerHTML="",l(a);const r=e.target.elements.search.value.trim();if(r!==""&&r!==m)i=1,m=r,await F();else return p.show({message:"Please complete the field!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}async function F(){try{f(d);const e=await x();E(e.hits);const s=h.querySelector(".photos-list-item").getBoundingClientRect();window.scrollBy({top:s.height*2,behavior:"smooth"}),y=Math.ceil(e.totalHits/g),f(a)}catch(e){console.log(e),p.error({message:"Sorry, an error occurred while loading. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}finally{l(d),b(),u.reset()}}async function $(){if(i>y)return l(a),p.error({theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight",message:"We're sorry, there are no more posts to load"});++i,await F()}function f(e){e.classList.toggle("hidden"),e.style.display="flex"}function l(e){e.classList.toggle("hidden"),e.style.display="none"}function b(){document.body.classList.add("loaded"),document.body.classList.remove("loaded_hiding")}
//# sourceMappingURL=commonHelpers.js.map
