import{a as w,i as l,S}from"./assets/vendor-b42c18af.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();async function x(){let e;a===1?e=$.value.trim().split(",").join("+"):e=c.trim().split(",").join("+"),console.log(e);const r=new URLSearchParams({key:"42633759-4a44573e34755b4488adb4c1b",q:[e],image_type:"photo",orientation:"horizontal",safesearch:!0,page:[a],per_page:[f]});return(await w.get(`https://pixabay.com/api/?${r}`)).data}function E(e){if(e.length==0)l.error({message:"Sorry, there are no images matching your search query. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"});else{const r=e.map(({largeImageURL:n,webformatURL:i,tags:t,likes:o,views:s,comments:L,downloads:P})=>`<li class="photos-list-item">
            <a class="photos-list-link" href="${n}">
            <img class="photo" src="${i}" alt="${t}"/>
            </a>
            <ul class="photo-information-container">
            <li class="item-photo-information-container"><p><span class="accent">Likes</span></br>${o}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Views</span></br>${s}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Comments</span></br>${L}</p></li>
            <li class="item-photo-information-container"><p><span class="accent">Downloads</span></br>${P}</p></li>
            </ul>
            </li>`).join("");h.insertAdjacentHTML("beforeend",r),q.refresh()}}const p=document.querySelector(".search-form"),$=p.elements.search,d=document.querySelector(".next-page-btn");u(d);const h=document.querySelector(".gallery"),q=new S(".gallery a",{captionsData:"alt",captionDelay:250}),m=document.querySelector(".loader");u(m);let a=1,f=15,g=Number,c="";window.onload=b;p.addEventListener("submit",v);d.addEventListener("click",O);async function v(e){e.preventDefault(),h.innerHTML="",F(m);const r=e.target.elements.search.value.trim();if(r!==""&&r!==c)a=1,c=r,await y();else return l.show({message:"Please complete the field!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}async function y(){try{const e=await x();E(e.hits),g=Math.ceil(e.totalHits/f),F(d)}catch(e){console.log(e),l.error({message:"Sorry, an error occurred while loading. Please try again!",theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight"})}finally{u(m),b(),p.reset()}}async function O(){if(a>g)return l.error({theme:"dark",progressBarColor:"#FFFFFF",color:"#EF4040",position:"topRight",message:"We're sorry, there are no more posts to load"});a+=1,await y()}function F(e){e.classList.toggle("hidden"),e.style.display="flex"}function u(e){e.classList.toggle("hidden"),e.style.display="none"}function b(){document.body.classList.add("loaded"),document.body.classList.remove("loaded_hiding")}
//# sourceMappingURL=commonHelpers.js.map
